version: "3"

services:
  app:
    build: .
    working_dir: /data/blog
    command: idyll
    ports: 
      - "3000:3000"
    volumes: 
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    container_name: idyll-blog